server:
  port: 9090

spring:
  cloud:
    gateway:
      routes:
        - id: Booking-Service
          uri: http://localhost:8083
          predicates:
            - Path=/busbooking/bookings/**,**/bookings
        - id: Booking-Service
          uri: http://localhost:8082
          predicates:
            - Path=/busbooking/schedules/**,/busbooking/seats/**,/busbooking/buses/**
        - id: Booking-Service
          uri: http://localhost:8081
          predicates:
            - Path=/busbooking/register,/busbooking/login,/busbooking/logout,/busbooking/users/**
